spring.application.name=mercadoexpress

server.port=8082

# Conexao com o Oracle FIAP

spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:oracle.fiap.com.br}:${DB_PORT:1521}:${DB_SERVICE:orcl}
spring.datasource.username=rm561497
spring.datasource.password=030606
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=USER